version: '3.9'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  etl:
    build: .
    depends_on:
      - minio
      - clickhouse
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: data
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
    volumes:
      - ./sample_data:/data

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
    ports:
      - "8501:8501"

volumes:
  minio_data:
  clickhouse_data:
